Latex Renderer + Tests
fb89zila/exam-repo_swe-sose21 pull request #15
Opened 2021-07-17 20:49 UTC by BerndSchmecka

Ok, der Test ist natürlich fehlgeschlagen, da der `LatexRenderer` noch nicht fertig war.
Ich habe jetzt aber eh soweit alles fertig gemacht und auch die Tests noch erstellt.

Was ich noch dazu sagen muss ist, dass ich bei `WriteLatexDocument` einen Parameter für den Pfad angegeben habe, damit wir das später besser mit dem outputPath Argument machen können.

Das mit den Lists und Quotes hab ich möglicherweise nen bisschen komisch gelöst, aber der Code scheint zu funktionieren^^

2021-07-17 23:52 UTC, fb89zila requested changes
Ok das hat jetzt gedauert.  
Was ich denke ich empfehlen würde ist, dass du nebenbei ein LaTeX-Dokument offen hast, welches du immer kompilieren kannst. Wenn du dann mal deine theoretischen Ausgaben Zeile für Zeile schreibst und kompilierst fällt das bestimmt eher auf.

Z.B. das es überhaupt nicht kompiliert würde so schnell auffallen.

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(0 <= value && value <= 3){
Also ich weiß nicht ob es das Wert ist hier eine Exeption zu werfen die behandelt werden muss UND die Markdownzeile zu verwerfen. Wieso sagst du nicht einfach, dass alles >3 gleich 3 ist?

Das selbe gilt bei den Quotes.

Kommt mir einfach unpraktisch vor.

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(0 <= value && value <= 3){
Siehe InList

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            File.WriteAllLines(path, LatexLines);
Ähh, wo ist der Rest?
- Erstellen eines Ordners mit `latexPath = Combine(path, "latex")` & `Directory.CreateDirectory(latexPath)`
- Eröffnungsbefehle, Indention, eventuelle Bibliotheken (hab jetzt nicht geguckt ob es welche braucht)... Halt alles was ein LaTeX Dokument braucht um überhaupt eins zu sein
- Erst danach `AppendAllLines()`
- Endbefehle

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +                    LatexLines.Add(caption); //Should also not happen
Should?  
Es ist eher unmöglich, da ich hier nie ein Match durchgebe welches nicht mit `#` beginnt^^

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(m == Match.Empty) {return;} //SHOULD never happen, but you never know ;D
Ok, ich denke in Kombination mit unseren anderen Klassen ist es sogar unmöglich.

Aber wieso machst du das nur hier und nicht in den anderen Fällen?

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(m == Match.Empty) depth = 0;
Wie gesagt, das wird nicht passieren, bzw. selbst wenn seh ich den Sinn dahinter nicht wirklich.

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(depth < InList){
Sagen wir du bist auf Ebene 3.  
Dein nächstes Listenitem ist auf Ebene 2. ==> Du springst auf Ebene 0.

Mach ne while-Schleife:
``` C#
while (depth < InList) {
    InList--;
}
```

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(InList == 0 && depth == 1){ //if not in any list
Ich glaube das es besser ist immer `depth >= [int]` zu benutzen.
Oder noch besser, nimm einfach
``` C#
if (InList == 0 && InList <= depth)
```
sonst gehen nur Zeilen verloren, wenn man ausversehen in Markdown 2 Leerzeichen zu viel hat (Markdown macht das übrigens genauso, es geht AB 2 Leerzeichen mehr immer in die nächste Ebene)

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            } else if (InList == 3){
``` C#
InList == 3 && InList <= depth
```

und das `if(depth == 3)` kann weg

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            } else if (InList == 1){
Im Zusammenhang mit der `while` Schleife von oben:  
Es braucht eine Möglichkeit nur eine Ebene runter zu steigen. Wir müssen also wissen was die **alte** `InList` war.  

Vorschlag mit Bsp.:  
- Wir sind in Ebene 2 und bekommen eine Zeile mit Ebene 1
- `while` Schleife sorgt dafür, dass depth = InList = 1
- ***neues privates Feld*** `oldInList`, welches am besten immer nach dem if-Baum den aktuellen `InList`-Wert annimmt = 2
- `newListAfterItem()` --> `newList()` + zusätzllichen `int` Parameter (einen Offset [0 - after item, 1 - index+1, 2 - index+2, ...])

``` C#
if (depth == 1 && oldInList > InList) {
    newList(content, oldList-InList);
} else if (depth == 1 && oldInList == InList) {
    appendNewItem(content);
} else {
    newList(content, 0);
}
```

- oldInList > InList --> `Insert` neue Liste beim Index des letzten Items + 2

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            LatexLines.InsertRange(LatexLines.FindLastIndex(x => x.StartsWith(@"\item"))+1, tmp);
Hier dann `x.StartsWith(@"\item")) + offset + 1`

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +        public static void WriteQuote(Match m){
All das von den Listen hier nochmal, nur halt angepasst (schrieb ich jetzt nicht^^)

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            LatexLines = new List<string>();
Theoretisch könntest du auch das, was ich bei `WriteLatexDocument()` für den Anfang des Dokumentes erwähnt habe, hier schon hinzufügen.  
Ist dir überlassen, was dir besser gefällt.

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestLatexRenderer.cs
> +        public void TestWriteList(){
Hier dann besonders das wechseln zwischen den Ebenen testen. Genauso bei Quotes.

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestLatexRenderer.cs
> +        public void TestBoldCursive(string mdinput, string texoutput){
Wenn du mal was testen willst, was zwar nie jemand machen würde, aber trotzdem geht ;D : 
``` latex
***a***b*c***d*e*f**g***h*i**j**k*l***m*n**o***p**q*r**s**t*u***v**w*x*y**z***

\textbf{\textit{a}}b\textit{c}\textbf{d\textit{e}f}g\textbf{\textit{h}i}j\textbf{k\textit{l}}m\textit{n\textbf{o}}p*\textit{q}r\textbf{s}t\textit{u}\textbf{v}w\textit{x}y\textbf{z}*
```

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestLatexRenderer.cs
> +        public void TestWriteLatexDocument(){
Mal abgesehen von der Sache mit dem "latex"-Ordner:  
Xunit Konvention ist es ein `expected` und `result` zu haben, selbst wenn es `expected = input;` ist

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestLatexRenderer.cs
> +        public void TestWriteLatexDocument(){
Müssen natürlich nicht 100% so heißen, also z.B. "expPath" wäre gut.
Mal abgesehen davon wäre eine richtige Unterteilung in `arrange`, `act` und `assert`, am besten mit Kommentaren, gut.

Alles nur formale Sachen, aber das machts halt übersichtlicher was der Test macht.

2021-07-17 23:52 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestLatexRenderer.cs
> +        public void TestWriteText(){
Viel Aufwand für einen solchen Test xD

2021-07-18 08:43 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(0 <= value && value <= 3){
Ok, stimmt, da hast du recht, ich besser das aus

2021-07-18 09:12 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            File.WriteAllLines(path, LatexLines);
Stimmt, die `\begin` und `\end` tags hab ich völlig übersehen

2021-07-18 09:13 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +                    LatexLines.Add(caption); //Should also not happen
Ja, ich hatte das nur aus Paranoia eingebaut, ist aber eigentlich nicht nötig

2021-07-18 09:15 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            if(m == Match.Empty) {return;} //SHOULD never happen, but you never know ;D
Das hatte ich irgendwann mal ganz am Anfang eingebaut gehabt. Später dann, als ich die anderen Methoden geschrieben habe, hab ich das dann weggelassen, weil es ja eigentlich nicht nötig wäre. Hier hab ich es wohl übersehen, kommt dann gleich mit weg

2021-07-18 12:18 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex.Test/TestLatexRenderer.cs
> +        public void TestWriteText(){
Ja, da bin ich mal nen bisschen kreativ mit dem input geworden xD

2021-07-18 12:23 UTC, BerndSchmecka commented
Ok, jetzt sollte ich eigentlich all dein Feedback adressiert haben. Bei `WriteLatexDocument()` hab ich noch den filename als Parameter hinzugefügt, damit dann von `MdToTex` aus dafür gesorgt werden kann, dass man entweder später den Dateiname als Argument angeben kann oder jetzt per default die .tex Datei immer genauso heißt wie die eingelesene .md file.

2021-07-18 17:29 UTC, fb89zila requested changes
Noch ein bisschen.

2021-07-18 17:29 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            List<string> latexDoc = new List<string>();
Wieso so umständlich?  
``` C#
File.WriteAllLines(latexPath, new string[] {
      @"\documentclass{scrreprt}",
      @"\setlength{\parindent}{0pt}",
      @"\newcommand{\quoteline}" + "\n",
      @"\begin{document}"
   }
);
File.AppendAllLines(latexPath, LatexLines);
File.AppendAllText(latexPath, @"\end{document}");
```

`AllLines()` ist speicherfreundlicher, da du bei `String.Join()` von `AllText()` eventuell einen riesen String im Speicher hast.

`AllText()` ist aber laut einem Typen auf StackOverflow schneller (allerdings nur 7% bei ~120.000 Zeilen), bestimmt da die eigendliche IO mit dem einzelnen String einfach schneller schreibt.

2021-07-18 17:29 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +        public static void WriteLatexDocument(string path, string filename){
Das mit dem Dateinamen ist eher kontraproduktiv besonders und auch so hier nicht komplett implementiert. (Momentan müsste ich in `MdToTex` den Dateinamen des Markdowns entfernen und extra mit `.tex` übergeben.)  
Wir haben hier 2 Möglichkeiten:
1. Wir gehen den Schritt zurück und geben immer den Markdownpfad durch
2. Wir schreiben es universell, also bauen gleich die Option eines optionalen Pfades ein und gehen deine Idee weiter

Im Fall von 2.:
``` C#
public static void WriteLatexDocument(string path){
            string latexPath;
            
            if (Path.GetExtension(path) == ".tex") {
                latexPath = path;
            } else if (Path.GetExtension(path) == ".md") {
                latexPath = Path.Combine(Path.GetDirectoryName(path), Path.GetFileNameWithoutExtension(path) + ".tex");
            } else {
                latexPath = Path.Combine(path, Path.GetFileNameWithoutExtension(MdToTex.mdFilePath) + ".tex");
            }

            Directory.CreateDirectory(latexPath);
...
```

Zum `else`, da kannst du im `MdToTex.mdFilePath` auf `internal` umschreiben.  
**Oder** wir machen es uns ganz einfach und sagen im `else`, `"latexDoc_01.tex"` oder sogar schon `"latexDoc_{num:000}.tex"` und danach `num++;` (für wenn wir Support für Verzeichnisse an Docs einbauen sollten, zerstört ja so nix)

2021-07-18 17:29 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            List<string> latexDoc = new List<string>();
Oh und, wenn ich das richtig verstehe sorgt das hier nur dafür den Text bei \quoteline{text} und einen Linebreak zu schreiben oder?

2021-07-18 17:29 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +        private static void newList(string content, int offset = 0){
Ich glaube hier brauchst du keinen Offset oder?

2021-07-18 17:29 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +        private static void newQuote(string content, int offset = 0){
Ebenso kein Offset?

2021-07-18 17:38 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            List<string> latexDoc = new List<string>();
Genau so ist es. Ich hatte gedacht, dass es besser wäre, nur eine Write-Operation für die Datei durchzuführen. Aber dass das speicherfreundlicher ist, wusste ich leider nicht, ich passe es mal an

2021-07-18 17:41 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +            List<string> latexDoc = new List<string>();
Naja, du hattest halt eine extra Liste + den Join()-String^^

2021-07-18 17:44 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/LatexRenderer.cs
> +        private static void newList(string content, int offset = 0){
Hast recht, was hab ich nur schon wieder gemacht xD

2021-07-18 18:08 UTC, BerndSchmecka commented
Ok, jetzt sollte (hoffentlich) wirklich alles passend sein. Ich hab es mal so gemacht, wie du vorgeschlagen hast mit dem `path` und auch `mdFilePath` auf `internal` gesetzt.

2021-07-18 18:15 UTC, fb89zila approved these changes
Müsste alles gewesen sein. Jetzt fehlt nur noch dein `void MdToTex.convertMathElement()` und dann können wir (glaube ich) richtig testen und eine v1.0 raushauen.

2021-07-18 18:15 UTC, merged