Calculator + MathParser (+ Tests)
fb89zila/exam-repo_swe-sose21 pull request #9
Opened 2021-07-15 08:37 UTC by BerndSchmecka

Während die Arbeit am `LatexRenderer` noch läuft, hier erstmal der `Calculator` + `MathParser`. Ich habe auch Tests für den `FuncCalculator` sowie (indirekt) auch für den `MathParser` integriert.

Noch als Anmerkung: Ich habe die RegEx der Single Variable Function geringfügig anpassen müssen, da sie das `/` zum Dividieren nicht erkannt hat (Ich hoffe, dass ich die RegEx nicht komplett zerstört habe, zumindest im Test läuft alles wie geplant xD)

2021-07-15 19:10 UTC, fb89zila requested changes
Puh, ok das war intensiv :D

Also erstmal muss ich anbringen das deine XML Kommentare Overkill sind.  
- Einzeilige Kommentare sollten auch einzeilig bleiben --> `/// <summary>eine zsmfassung</summary>`
- Beschreibe die Parameter in `summary` mit `<paramref>` anstatt extra Zeilen mit `<param>` zu verschwenden. Das ist nur dafür wenn es **absolut** notwendig ist es extra zu erklären, weil es besonders kompliziert ist.
- Ich weiß nicht ob es wirklich nötig ist mit einer massiven Liste die RegEx zu beschreiben, wenn wir [das hier](https://github.com/fb89zila/exam-repo_swe-sose21/wiki/Developer#used-regular-expressions-) haben. Ich füge nochmal die Dictionary-Keys hinzu, aber in die Klassendocu gehört das eigendlich nicht.

---

Ansonsten hab ich alles in die Kommentare geschrieben. Bei dem massiven Kommentarblock in `FuncCalculator` ist nur der 2, und 3. Teil wichtig, aber insgesamt ist das meine Gedankenflut die sich in viel Text wiederspiegelt.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/SingleVarCalculator.cs
> +        /// <param name="vars">The variable to use.</param>
Ist es wirklich nötig die hier (und in den anderen Fällen) nochmal zu erklären, wenn du es schon in `<summary>` gemacht hast?

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +            mathrx = new Dictionary<string, Regex>();
Als Initalisierungssyntax geht es bei Collections auch wie mit Arrays, also:
```
mathrx = new Dictionary<string, Regex>()
            {
                {"", new Regex(@"")},
                {"", new Regex(@"")},
                ...
                {"", new Regex(@"")}
            };
```
Nicht wirklich schlimm, aber sieht finde ich besser aus^^

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +            mathrx.Add("svfunction", new Regex(@"f\(([a-z]|[\d\.]+)\)=([\d\^\+\-\*\/\\a-z]*):([a-z])"));
Ah, ich bin blöd. Logisch erkennt die das nicht, da ich \\ als Division angegeben habe.  
Also anstatt `\/\\` brauchst du nur `\/`

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestMarkdownParser.cs
> -        [InlineData(@"D:\Felix\Documents\_projects\C#\SWE_Prufung\exam-repo_swe-sose21\MarkdownToLatex\MarkdownToLatex.Test\test_files\test1.md")]
Hab ich schon selber ausgebessert. Nächstes mal sagst du's einfach wenn bei mir was nicht stimmt (oder ich bekomm es selber durch die Test-Action raus).  
Sonst gibt es nur Konflikte die extra gelöst werden müssen.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestMarkdownParser.cs
> -        [InlineData(@"D:\Felix\Documents\_projects\C#\SWE_Prufung\exam-repo_swe-sose21\MarkdownToLatex\MarkdownToLatex.Test\test_files\test1.md")]
Ah, das heißt übrigens, dass du die Datei mit `git restore` einfach zurücksetzen kannst

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +            this.Variable = char.Parse(vars.Substring(0, 1));
Wieso nicht einfach `char.Parse("a");`?  
längeres sollte sowieso eine Exeption werfen.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return null;
Hmm? geht hier `return null;` wenn es strings zurückgibt?

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Die Idee mit dem "erst Funktion mit Parameter und dann erst eingesetzt mit Ergebnis" ist gut gedacht, aber ich würde es anders formatieren. Um genau zu sein müssen wir hier extrem gut überlegen.
Da wir sowieso mit RegEx arbeiten könnte es aber recht einfach gehen.
``` C#
return $"f({vars})=" + func.ToLaTeX() + "\n"
$"f({param.ToString(CultureInfo.InvariantCulture)})=" + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
```
Mit sowas wie:
```regex
((.+)(\\n)(.+))*
```
könnest du dann direkt in `MdToTex.convertMathElement()` `\n` mit `Regex.Replace(in, pattern, replacement)` ersetzen und vorn & hinten `\[` bzw. `\]` setzen oder du arbeitest mit `\begin` und `\end` Blöcken

---

Vielleicht kannst du auch noch [hier](https://www.overleaf.com/learn/latex/Aligning_equations_with_amsmath) drüber nachdenken, aber das ist optional.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return null;
Vllt wäre es besser eine bestimmte Exeption zu werfen? evtl. eine eigene.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestCalculators.cs
> +            Match mathMatch = MarkdownParser.MatchMathElement("! f(12.43)=x^2+5*x-11/10:x");
??? Wieso testest du hier meine Match Klasse? Calculater wird nie den Markdown-String sehen und bekommt immer gleich den func-string.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestCalculators.cs
> +            Match mathMatch = MarkdownParser.MatchMathElement("! f(12.43)=x^2+5*x-11/10:x");
Bzw. schon `MdToTex.convertMathElement()` bekommt nur das mathematische Objekt als `string`.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Oh und nebenbei, vllt. wäre es besser die Berechnung in eine eigene Methode zu stecken (selbst wenn es nur eine Zeile ist). Dann könnte man in der abstrakten Oberklasse die Convert-Methoden verallgemeinern und nur eine `Calculate()` Methode, welche je nach Funktion überschrieben wird, in die speziellen Calculators einbauen.
Bzw. man könnte auch gleich ein `delegate` anlegen, damit man `Calculate()` und eventuell später Methoden wie `CalcRoot()` usw. nur hinzufügen muss. Ergebnisse sollten ja eigentlich eh in ein Property.

Vorteil wäre, dass man bei `Calculate()` einfach einen `double` zurück bekommt, den man in die Convert-Methode einsetzt. Dadurch kann man die separat testen.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> -    public class Calculator
Ich weiß nicht ob ich es vergessen habe anzubringen, aber vllt. wäre hier oder in den Unterklassen noch ein Property `CalcResult {get; protected set;}` gut. Ich hatte ja erwähnt das es vllt besser ist hier nur zu berechen.

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Ok rollback, Idee:

Wie bereits erwähnt wollte ich alle möglichen Ergebnisse berechnen und diese dann auf Anfrage durch Parameter in Markdown zurückgeben.  
Wenn wir die Berechnung wie gerade gesagt, durch ein Delegate umsetzen, dann brauchen wir ja nur den `func.ToLaTeX()` Part in den Convert-Methoden stimmts?  
Wenn wir jetzt also in `MdToTex.convertMathElement()` je nach Match aus `MathParser` nur den jeweiligen `Calculator` in einem `switch case` anlegen können wir dannach ein weiteres `switch case` benutzen um Parameter aus dem Match abzufragen (wenn die RegEx's angepasst sind in glaube `MatchMathElement().Groups[2]`).
Also:
- `switch case` für Calculator
- Convert Methode -> `WriteMathElement`
- `switch case` mit fallthrough (auch wenn [umständlich](https://stackoverflow.com/questions/174155/switch-statement-fallthrough-in-c/174223#174223) in C#) für die Parameter und jeweils `WriteMathElement`

Das sichert das alles in eine neue Zeile kommt. Und keine hässlichen aneinanderklebenden Funktionen rauskommen (und alles ohne umständliches `Replace()`)

2021-07-15 19:10 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex.Test/TestCalculators.cs
> +        private readonly Xunit.Abstractions.ITestOutputHelper hlp;
Wozu?

2021-07-15 19:12 UTC, fb89zila commented
Hier ist es jetzt übrigens besonders wichtig, dass du mir sagst wenn ich mir irgendwas falsch gedacht habe.  
Ist jetzt viel mit einmal, aber wir sollten uns besonders beim den `Calculator` Klassen gedanken um Erweiterbarkeit machen.

2021-07-15 19:39 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +        public static Dictionary<string, Regex> mathrx {get;}
Fast vergessen: `public` --> `MathRx` statt `mathRx`

2021-07-15 19:40 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +        public static Dictionary<string, Regex> mathrx {get;}
Ich schreib das auch so ins Wiki

2021-07-16 06:30 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/SingleVarCalculator.cs
> +        /// <param name="vars">The variable to use.</param>
Ich war der Meinung, dass es 'best practise' wäre, so viel wie möglich zu dokumentieren. Aber ja, könnte unübersichtlich wirken, ich werde es entfernen.

2021-07-16 06:31 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +            mathrx = new Dictionary<string, Regex>();
Wird gemacht

2021-07-16 06:31 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +            mathrx.Add("svfunction", new Regex(@"f\(([a-z]|[\d\.]+)\)=([\d\^\+\-\*\/\\a-z]*):([a-z])"));
Ok, danke, hatte mich schon gewundert, warum es einfach nicht klappen wollte

2021-07-16 06:32 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex.Test/TestMarkdownParser.cs
> -        [InlineData(@"D:\Felix\Documents\_projects\C#\SWE_Prufung\exam-repo_swe-sose21\MarkdownToLatex\MarkdownToLatex.Test\test_files\test1.md")]
Hab das selber auch erst spät beim Test bemerkt. Hab mir jetzt einfach die aktuelle Version der Datei aus dem `master` reingemerged.

2021-07-16 06:33 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +            this.Variable = char.Parse(vars.Substring(0, 1));
Keine Ahnung, wollte einfach eine 'doppelte Absicherung' haben, ist aber eigentlich unnötig.

2021-07-16 06:33 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return null;
Wird erstellt.

2021-07-16 06:35 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex.Test/TestCalculators.cs
> +            Match mathMatch = MarkdownParser.MatchMathElement("! f(12.43)=x^2+5*x-11/10:x");
Hier wollte ich einfach mal einen breiteren Test anlegen. Ja, der gehört dann eigentlich nicht in die `TestCalculators` rein, ich werde ihn auch wieder entfernen, aber war trotzdem mal ganz gut zu wissen, ob das Matchen im Zusammenspiel mit dem Calculator gut funktioniert.

2021-07-16 06:36 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex.Test/TestCalculators.cs
> +        private readonly Xunit.Abstractions.ITestOutputHelper hlp;
War zum Debuggen meiner Tests gedacht, hab ich leider vergessen gehabt, nach dem Debuggen wieder zu entfernen. Das fliegt jetzt direkt mit raus.

2021-07-16 06:38 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +        public static Dictionary<string, Regex> mathrx {get;}
Mist, eigentlich kenne ich die Naming Conventions sehr gut, schaffe es aber trotzdem jedes mal, die im entscheidenden Moment aus Gewohnheit zu ignorieren. Jetzt heißt es `MathRx`

2021-07-16 07:12 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Ich hätte dazu vielleicht auch noch eine Idee, die Interessant sein könnte:

Und zwar könnten wir auch den Calculator Generic machen (also z.B. `Calculator<T, U, V>`, wobei dann T sagt, was die Variable ist, die in den Calculator reingeht, U was der/die Parameter ist/sind und V was das Ergebnis ist). Damit könnte man ConvertElement bis auf die höchste Ebene abstrahieren (als `ConvertElement(T var, string element)` bzw. `ConvertElement(U param, T var, string element)`) und deine Vorgeschlagene Property dann als `public V CalcResult {get; protected set;}` implementieren. Damit könnten wir auch so gedöns wie den `SingleVarCalculator` komplett entfernen, da der dann obsolet werden würde. Den `FuncCalculator` lassen wir dann einfach von `Calculator<char, double, double>` oder so erben. Für MultiVariable zeugs dann entsprechend von z.B. `Calculator<char[], double[], double>`.

2021-07-16 07:14 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Damit hätten wir dann auch eine maximale Erweiterbarkeit, da man im Prinzip jeden Datentyp dort angeben kann, solange man die passende `ConvertElement` Methode implementiert.

2021-07-16 09:06 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> -    public class Calculator
Ja, können wir so machen (siehe dann oben meinen Vorschlag zum Datentyp)

2021-07-16 13:30 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Oh wow, ich hab überhaupt nicht daran gedacht das man das als Generic implementieren könnte. Sehr gute Idee.

Ich hab auch nochmal nachgedacht wegen den Parametern. Wenn wir die sowieso einzeln abfragen brauchen wir auch keine Properties für die einzelnen Ergebnisse.

Also auf deiner Idee aufbauend:
- Calculator zu Generic, die S/MVarCalc. weg
  - Input und Variablen als Generic ist gut, aber Ergebnis kann von Methode zu Methode unterschiedlich sein (z.B. Vektorenrechnungen Scalar)
  - Element bleibt `string`
  - Konstruktor für Erstellung des calc

![calc](https://www.plantuml.com/plantuml/svg/PL9DJyCm3BtdL_Z69jfAkqwZJ9hWWeQGwE0ukQtNLSiSb3WRqjZVuW_mnqZRVK8kIUpdz-oNZ9sW5R_MW0fp9nOBWGdgmciKOqTPD4jXfo2isv2jkO87JMjYWT6e8adJBfV12rfSNmTdy8RsAZIVpxlKxYYsXmFjnF26h1pOU_qMboH5w299sikvhLvs3n-jtXsmrpg26MpGHaSkwaZwQgzKeT4vUFHSdEj3JwNnkQPZHNeQiekVjAZNajmy6o6d58SDq04Fr3inmxQsu0nGpSJmP3Ym-LKZGDO9QKqSgTNFDpVf1blMr7XIOwDH10se6QPbPZBw16HD5R7oN49kqHVBKCNUjlJ__84foTAKf0B3bdG0jq2e5_6heBHFXFd2OYLWyeDTcWAgTf8e2YBDD66c0SIQ5X9V63mSdizANHht5ST_p5JZm1L-q2y0)

![flow](https://www.plantuml.com/plantuml/svg/JKz13i8m3Blt5JaEYHD7Tfc4E4xY2rbhwAIkHKasla_B1EBY99OjEuCQYwrB8Zwvp-xElkGDOYDRl2OioDQfoPmVXFqyz5KaO0DvJfvUiqNIYZvMGh4JpNzZKOZhHbWiGKbWgsIQIab7cbOZ3e5AdKyMNc0GkXTfLXzRocMlygtHgF-SflqvjNV8mGqLwZzl)

### Wenn ich was vergessen habe sag Bescheid.

2021-07-16 13:37 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
[Das hier](regexr.com/61ofg) wäre der neue RegEx mit dem ich die Markdown Mathe erkenne.

2021-07-16 13:47 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Weißt du was, umsonst gibt es `String.Equal()` ja nicht. Ich mach das jetzt einfach mit vollen Worten. (auf Link angepasst)

2021-07-16 15:15 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Cool, dass du direkt nen schönes UML dafür erstellt hast^^ 

Ich hätte nur eine kleinere Rückfrage bezüglich der `Calculate()`-Methode. Also wenn ich das richtig verstanden habe, soll quasi die abstrakte `ConvertElement()` dann in der abgeleiteten Klasse die `Calculate()`-Methode aufrufen und deren Ergebnis dann als LaTeX zurückgeben, richtig? 

Da wäre dann allerdings das Problem, der `ConvertElement()` mitzuteilen, welche der `Calculate()` Methoden gewünscht wird. Ich hatte überlegt, das mit nem Delegaten zu machen, aber da müssten alle `Calculate()` Methoden den selben Rückgabetyp haben, was aber nicht geht(z.B. `Calculate()` gibt ja `double` zurück, aber `CalculateDerivative()` (nur als Beispiel) würde ja `string` zurückgeben.

2021-07-16 15:44 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Dein 2. Paragraph ist richtig.
Wie meinst du "welche der `Calculate`"? Es gibt nur die eine.

2021-07-16 15:49 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Achso, ich hab irgendwie gedacht, dass da später welche hinzukommen. Wenn es nur eine gibt, ist alles klar ;)
Übrigens musste ich den Konstruktor vom `Calculator` überladen (Einmal mit `param`, einmal ohne, weil C# offenbar keine Lust hatte, `null` als Standardwert für `T?` festzulegen)

2021-07-16 15:55 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Hast du richtig gelesen was ich geschrieben habe?
Es gibt 2 `switch case` und zwischen denen die Konvertierung mit eventuellem Ergebnis:
1. Zur Erstellung des jeweiligen `Calculator` mittels `switch (MarkdownParser.MatchMathElement(element).Groups[1])`
2. (in einer `foreach` von der Parameter MatchCollection) Endparameter --> Weitere Calculate-Methoden werden ausgeführt

2021-07-16 15:58 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
> Konstruktor vom Calculator überladen

Hab ich irgendwie erwartet, Habs auch nicht getestet gehabt, aber Überladung ist ja kein Problem.

2021-07-16 16:05 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Und [hier](https://regexr.com/621hl) wäre das RegEx was ich meine. Kannst du eigentlich gleich als `MatchCollection MatchParameters(string params)` in den `MathParser einbauen`.

Mal sehen, was hältst du vom Key `"params"`?

2021-07-16 16:15 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
> Mal sehen, was hältst du vom Key `"params"`?

Ja, wäre ok

2021-07-16 16:25 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Ok, noch eine letzte Rückfrage: Die Formatierung des strings, der bei `ConvertElement()` rauskommt, soll wie oben stattfinden?

2021-07-16 16:31 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Hab vergessen hier zu sagen wie ich die Konvertierung meine.  
Zwischen den `switch case` wird direkt die `ConvertElement()` Methode aufgerufen. Dort integriert ist die `Calculate()` Methode (`if (Param != null)` oder ähnliches).

## ODER

Neue Idee: Wir machen das berechnen des Ergebnisses auch optional mittels `{result}`-Parameter. Dann ist `ConvertElement()` wirklich nur das konvertieren.

**Vorteil** wäre, dass es einfach ist das konvertierte Element und das Ergebnis in separate Zeilen zu schreiben.  
Das von deinem Code:
``` C#
return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
```
würde wenn du wie geplant nur die `\[\]` oder was du benutzen möchtest hinzufügst so aussehen:  
![latex](https://latex.codecogs.com/png.image?\bg_white&space;f(1)&space;=&space;x^2&plus;x-\frac{2}{3}&space;with&space;f(1)&space;=&space;\frac{4}{3})  
D.h. du müsstest das erst wieder trennen wie ich schon ganz oben erwähnt hatte.

**Nachteil** wäre, dass es eine Exeption geben muss, wenn `{result}` gewählt wurde, es aber keinen Parameter gibt (außer wir sagen es wird automatisch `0`)

2021-07-16 16:32 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Damit hab ich hoffe auch deine letzte Frage beantwortet?

2021-07-16 16:33 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
Sag einfach was du machen möchtest.

2021-07-16 17:26 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return $"f({vars}) = " + func.ToLaTeX() + $" with f({param.ToString(CultureInfo.InvariantCulture)}) = " + func.Compile(vars)(param).ToString(CultureInfo.InvariantCulture);
> Damit hab ich hoffe auch deine letzte Frage beantwortet?

Ja, danke. Sorry, dass ich so viele Fragen stelle, aber ich will einfach sicherstellen, dass ich zu 100% gleich alles richtig mache, bevor ich erst groß irgendwas schreibe, was ich dann verwerfen müsste.

> Sag einfach was du machen möchtest.

Also ich fände, dass die neue Idee ziemlich gut ist. Auch der Teil `(außer wir sagen es wird automatisch 0)` klingt gut, dann würde man ja quasi die Schnittstelle mit der y-Achse erhalten, falls man keinen Parameter angibt, aber ein Ergebnis haben will.

2021-07-16 17:33 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +        public static Match MatchSVFunction(string element) {
Wow, warte. Ich weiß nicht wie ich das übersehen habe, aber was machst du hier eigentlich???
Ich wollte nur gerade was gucken für das Klassendiagramm was ich gerade überarbeite, aber
``` C#
return MathRx["svfunction"].Match(text);
```
reicht völlig. `svfunction` ist hardcoded, der Wert kommt immer zurück.

2021-07-16 17:45 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/MathParser.cs
> +        public static Match MatchSVFunction(string element) {
Ok danke, wird behoben. Keine Ahnung, wie ich auf die Idee gekommen bin, dass der Wert eventuell nicht da sein könnte ;)

2021-07-16 17:50 UTC, BerndSchmecka commented
So, *eigentlich* sollte jetzt alles da sein. Wenn ich bei all der Textflut irgendwas wichtiges vergessen habe, sag mir das dann bitte, damit ich es nachliefern kann.

2021-07-16 17:53 UTC, fb89zila commented
Kurze Frage, hast du einen `git rebase` gemacht? Die `TestMarkdownParser.cs` ist immer noch da. Oder ist das ne Github Sache?

2021-07-16 17:55 UTC, BerndSchmecka commented
Ich hab mittels `get merge master` in den `calculator` Branch die aktuelle Version vom `master` reingemerged und damit sollte eigentlich die aktuelle Version der `TestMarkdownParser.cs`da sein

2021-07-16 18:48 UTC, fb89zila commented
In dem Fall den wir habe ist `rebase` besser glaube ich, da wir ja getrennt die Klassen erstellen und unsere "Basis" `master` immer nur erweitern. Mir kommt es halt komisch vor, dass es als als geändert angezeigt wird.

2021-07-16 19:43 UTC, fb89zila requested changes
Zum Großteil nur Kleinigkeiten.  
Nur in `MathParser` hast du vergessen die `MatchCollection MatchParameters(string params)` zu implementieren. ([RegEx war hier](https://regexr.com/621hl))  

Danach musst du den Test wieder leicht abändern, aber bei manchen Sachen weiß ich nicht wieso du das überhaupt geändert hast (z.B. all das mit `System.Globalization`)

2021-07-16 19:43 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +    /// <summary>The basic calculator class. <typeparamref name="T"/> specifies the parameter/s to use and cannot be a reference type. <typeparamref name="U"/> specifies the variable/s to use.</summa
Haha, ich glaube du hast mich falsch verstanden mit den XML-Kommentaren, ich hatte das mit dem "auf eine Zeile schreiben" nur gesagt, weil du ***alles*** auf mehrere Zeilen geschrieben hast xD
Solche riesigen Kommentare kannst du ruhig über mehrere Zeilen schreiben, bzw. da Markdown in den Kommentaren funktioniert ist es eher besser.
Ist nichts schlimmes, aber fürs nächste mal.

2021-07-16 19:43 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +        protected Calculator(U var, string element, T? param = null){
Komische Anordnung der Parameter. wieso nicht `T, U, string` oder von mir aus `string, T, U`?

2021-07-16 19:43 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +#nullable disable
?

2021-07-16 19:43 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return func.ToLaTeX();
Wo ist `$"f({Vars}) = "` ?

2021-07-16 19:43 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +        public FuncCalculator(string var, string element, double? param = null) : base(var, element, param){}
Hier dann auch mit der Ordnung

2021-07-16 19:43 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return func.Compile(this.Var)(this.Param ?? 0);
Wir müssen das hier schon zu LaTeX konvertieren, da das von `MdToTex` gerufen wird. In dem Sinne:  
``` C#
return $"f({this.Var})=" + Math.Round(func.Compile(this.Var)(this.Param ?? 0), 2).ToString(CultureInfo.InvariantCulture);
```

2021-07-16 19:43 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return func.ToLaTeX();
Also
``` C#
return $"f({this.Var})=" + func.ToLaTeX();
```

2021-07-16 19:53 UTC, fb89zila commented
Klassendiagramm im Wiki ist angepasst. Wenn ich nichts übersehen habe kannst du da auch kucken ob du alles hast.

2021-07-16 20:24 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +    /// <summary>The basic calculator class. <typeparamref name="T"/> specifies the parameter/s to use and cannot be a reference type. <typeparamref name="U"/> specifies the variable/s to use.</summa
Ja, ich muss noch lernen, die Dokumentationen platzmäßig gut zu verteilen, aber langsam wird's xD

2021-07-16 20:27 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +        protected Calculator(U var, string element, T? param = null){
Da hatte sich bei mir VS Code aufgeregt, dass der Parameter mit Standardwert ganz zum Schluss kommen muss.
`Optionale Parameter müssen nach allen anderen Parametern angezeigt werden.` meinte er. Das war dann auch nicht nur eine Warnung, der wollte dann gar nicht mehr kompilieren

2021-07-16 20:30 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +#nullable disable
Ich dachte, dass nach einem `#nullable enable` auch das passende disable kommen muss, wie z.B. mit den `\begin` und `\end` Tags. Anscheinend ist dem aber nicht so, ich entferne das mal

2021-07-16 20:30 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +                return func.ToLaTeX();
Jap, das meinte ich mit vergessen xD Danke fürs Hinweisen^^

2021-07-16 20:33 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +        protected Calculator(U var, string element, T? param = null){
Ok komisch, naja solange es funktioniert.  
Ich glaube hier wäre ein guter Fall die Parameter in der docu zu erklären.

2021-07-16 20:35 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +#nullable disable
Ne allgemein, mich wundert es das du das benutzen musstest, nicht wie du es benutzt hast

2021-07-16 20:37 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +#nullable disable
Da hatte sich auch VS Code aufgeregt, dass Nullables hier nicht verwendet werden können und ich die doch bitte in einen `#nullable`-Block stecken solle. Warum das so ist, weiß ich auch nicht, aber so funktionierts auf jeden Fall

2021-07-16 20:40 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +#nullable disable
Ich wusste halt nicht mal das es sowas gibt :D

2021-07-16 20:41 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/Calculator.cs
> +#nullable disable
Ich auch nicht, bis VS Code mir das erzählt hat ^^

2021-07-16 20:57 UTC, BerndSchmecka commented
Ok, laut Klassendiagramm sollte jetzt wirklich alles da sein

2021-07-16 21:30 UTC, fb89zila reviewed
Alles gut. Mein Kommentar kannst du gleich noch anbringen oder später.  
Das Mergen überlass ich dir, da brauchst du nicht nochmal ein Review anfragen.

2021-07-16 21:30 UTC, fb89zila commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +        public string Calculate(){
Idee für Erweiterbarkeit: Parameter `int precision = 2` (oder 3) für `Math.Round`.

Kannst du auch nach einem merge als mini update machen.

2021-07-16 21:30 UTC, fb89zila approved these changes

2021-07-17 07:34 UTC, BerndSchmecka commented on MarkdownToLatex/MarkdownToLatex/FuncCalculator.cs
> +        public string Calculate(){
Gute Idee, bau ich direkt mit ein ^^

2021-07-17 07:38 UTC, merged